peerDependencyRules:
  ignoreMissing:
    - scheduler
ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - node-pty
allowedDeprecatedVersions:
  ldapjs: "3.0.7"
packages:
  - 'base'
  - 'web'
  - 'native'
  - 'dns'
  - 'webpack'
  - 'nodejs'
  - 'sourceMap'
  - 'snippet'
  - 'ldap'
  - 'jest'
  - 'webshell'
  - 'rpc/*'
  - 'packages/*'
allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  ffi-napi: true
  node-pty: false
  ref-napi: true
