allowedDeprecatedVersions:
  ldapjs: "3.0.7"
packages:
  - 'base'
  - 'web'
  - 'native'
  - 'dns'
  - 'webpack'
  - 'nodejs'
  - 'sourceMap'
  - 'snippet'
  - 'ldap'
  - 'jest'
  - 'webshell'
  - 'trpc'
  - 'packages/*'
